server.port: 8084
spring:
  application:
    name: service4
  sleuth:
    propagation:
      type: W3C
    baggage:
      remote-fields:
        - key
      correlation-fields:
        - key
        - newField
      local-fields:
        - key
        - newField
      tag-fields:
        - key
        - newField
    otel:
      log:
        exporter:
          enabled: true
        slf4j:
          enabled: true
      propagation:
        composite-text-map-propagator:
          enabled: true
      config:
        trace-id-ratio-based: 1.0

logging.level.org.springframework.cloud.sleuth: DEBUG

management.endpoints.web.base-path: /
management.endpoints.web.exposure.include: "*"

logging.pattern.level: "%5p [${spring.zipkin.service.name:${spring.application.name:}},%X{traceId:-},%X{spanId:-},%X{key:-},%X{newField:-}]"

wavefront.application.name: sleuth-documentation-apps
wavefront.application.service: service4
